import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { BsChevronDown } from "react-icons/bs";

import HeroImage from "../assets/images/hero_image.png";

export default function Home() {
	return (
		<div className="App">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="App">
				<section className={styles.hero}>
					<div className={styles.hero__container1}>
						<h1>
							Rent a car, <br /> pull up in style{" "}
						</h1>
						<section className={styles.ctas}>
							<article>
								<div className={styles.cta}>
									<p className={styles.title}>Manufacturer</p>
									<div className={styles.option__container}>
										<p className={styles.option}>Toyota</p>
										<BsChevronDown style={{ fontSize: "12px" }} />
									</div>
								</div>
								<div className={styles.cta}>
									<p className={styles.title}>Type</p>
									<div className={styles.option__container}>
										<p className={styles.option}>SEDAN</p>
										<BsChevronDown style={{ fontSize: "12px" }} />
									</div>
								</div>
							</article>
							<button>Find car</button>
						</section>
					</div>
					<div className={styles.hero__container2}></div>
					<div className={styles.hero__image}></div>
				</section>
			</main>
		</div>
	);
}
